default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  host: db
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: event_cross_development

test:
  <<: *default
  database: event_cross_test
