# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 257a9f5f998945a9fa79facf3767e4b3d1b6f4121f76a074ab68018c1b77c8bd3c3d671c6263e9f98b5e8bb0e0fc435255d49e643eb16794b6b6c5778544d3b7

test:
  secret_key_base: dbbe910785bdba4fdacedeb6970144415179bc2eeb54e00dc9eb989deaf5a35e68acca595de78d09e6b76cf671e3c98bc0256f59819a60b64e15d4756a6ad3ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
